version: 2

sources:
    - name: staging
      #For bigquery:
      database: citibike-31437
      schema: citibike_data_all
      # loaded_at_field: record_loaded_at
      tables:
        - name: citibike_table_partitioned

